#!/bin/sh

DIR="$HOME/.okmtyuta/oksh"

if [ ! -e "$DIR/command/target/release/command" ]; then
    cd "$HOME/.okmtyuta/oksh/rscommand" && cargo build -r
fi

"$HOME/.okmtyuta/oksh/rscommand/target/release/rscommand" $@
